"""init schema

Revision ID: bfbb9d4bc131
Revises: 
Create Date: 2025-11-18 20:18:18.071849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfbb9d4bc131'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('avg_volume', sa.Float(), nullable=True),
    sa.Column('volume_spike', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'symbol')
    )
    op.drop_index(op.f('ticks_symbol_ts_idx'), table_name='ticks')
    op.drop_index(op.f('ticks_ts_idx'), table_name='ticks')
    op.drop_table('ticks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'ts', 'id', name=op.f('ticks_pkey'))
    )
    op.create_index(op.f('ticks_ts_idx'), 'ticks', [sa.literal_column('ts DESC')], unique=False)
    op.create_index(op.f('ticks_symbol_ts_idx'), 'ticks', ['symbol', sa.literal_column('ts DESC')], unique=False)
    op.drop_table('analytics')
    # ### end Alembic commands ###
